const ACTIONS = {
  IS_LOGGED: "IS_LOGGED",
  ALERT: "ALERT",
  CLEAR_ALERT: "CLEAR_ALERT",
  TRANSITION: "TRANSITION",
  ADD_CATEGORY: "ADD_CATEGORY",
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  EDIT_CATEGORY: "EDIT_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  TASKS_COUNT: "TASKS_COUNT",
  EDIT_CATEGORY_IN_TASK: "EDIT_CATEGORY_IN_TASK",
  AUTH_DIALOG: "AUTH_DIALOG",
};

export default ACTIONS;
